// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvdZG88uA1zYvdeM7nVAnWxrxCWiVqCWY',
    appId: '1:233003816790:web:9b9569577dedceb9bae8f7',
    messagingSenderId: '233003816790',
    projectId: 'keepit-cf68b',
    authDomain: 'keepit-cf68b.firebaseapp.com',
    storageBucket: 'keepit-cf68b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm-3JsZI5gwNqTQqqMyaDMfAHaEwkYMPQ',
    appId: '1:233003816790:android:f37a72a10bc14baabae8f7',
    messagingSenderId: '233003816790',
    projectId: 'keepit-cf68b',
    storageBucket: 'keepit-cf68b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB9-ICretxEWjWAJwlTjA-7tceZWxroHU',
    appId: '1:233003816790:ios:5931e17611533552bae8f7',
    messagingSenderId: '233003816790',
    projectId: 'keepit-cf68b',
    storageBucket: 'keepit-cf68b.appspot.com',
    iosBundleId: 'com.example.keepit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB9-ICretxEWjWAJwlTjA-7tceZWxroHU',
    appId: '1:233003816790:ios:07f86498b57d2a94bae8f7',
    messagingSenderId: '233003816790',
    projectId: 'keepit-cf68b',
    storageBucket: 'keepit-cf68b.appspot.com',
    iosBundleId: 'com.example.keepit.RunnerTests',
  );
}
